[tool.poetry]
name = "taglogger"
version = "1.0.0"
description = "Simple Bot for notify you in a Group when you were Tagged"
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
Pyrogram = "^2.0.30"
TgCrypto = "^1.2.3"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pylint = "^2.14.4"
pre-commit = "^2.19.0"
isort = "^5.10.1"
pyclean = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
